package main

import (
	"github.com/aws-support/mcp-server/config"
	"github.com/aws-support/mcp-server/models"
	tools_x_amz_target_awssupport_20130415_refreshtrustedadvisorcheck "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_refreshtrustedadvisorcheck"
	tools_x_amz_target_awssupport_20130415_addcommunicationtocase "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_addcommunicationtocase"
	tools_x_amz_target_awssupport_20130415_describetrustedadvisorchecks "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_describetrustedadvisorchecks"
	tools_x_amz_target_awssupport_20130415_describecreatecaseoptions "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_describecreatecaseoptions"
	tools_x_amz_target_awssupport_20130415_describesupportedlanguages "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_describesupportedlanguages"
	tools_x_amz_target_awssupport_20130415_describetrustedadvisorcheckrefreshstatuses "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_describetrustedadvisorcheckrefreshstatuses"
	tools_x_amz_target_awssupport_20130415_resolvecase "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_resolvecase"
	tools_x_amz_target_awssupport_20130415_describeservices "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_describeservices"
	tools_x_amz_target_awssupport_20130415_describecommunications "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_describecommunications"
	tools_x_amz_target_awssupport_20130415_createcase "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_createcase"
	tools_x_amz_target_awssupport_20130415_describecases "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_describecases"
	tools_x_amz_target_awssupport_20130415_describeseveritylevels "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_describeseveritylevels"
	tools_x_amz_target_awssupport_20130415_addattachmentstoset "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_addattachmentstoset"
	tools_x_amz_target_awssupport_20130415_describetrustedadvisorcheckresult "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_describetrustedadvisorcheckresult"
	tools_x_amz_target_awssupport_20130415_describeattachment "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_describeattachment"
	tools_x_amz_target_awssupport_20130415_describetrustedadvisorchecksummaries "github.com/aws-support/mcp-server/tools/x_amz_target_awssupport_20130415_describetrustedadvisorchecksummaries"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_awssupport_20130415_refreshtrustedadvisorcheck.CreateRefreshtrustedadvisorcheckTool(cfg),
		tools_x_amz_target_awssupport_20130415_addcommunicationtocase.CreateAddcommunicationtocaseTool(cfg),
		tools_x_amz_target_awssupport_20130415_describetrustedadvisorchecks.CreateDescribetrustedadvisorchecksTool(cfg),
		tools_x_amz_target_awssupport_20130415_describecreatecaseoptions.CreateDescribecreatecaseoptionsTool(cfg),
		tools_x_amz_target_awssupport_20130415_describesupportedlanguages.CreateDescribesupportedlanguagesTool(cfg),
		tools_x_amz_target_awssupport_20130415_describetrustedadvisorcheckrefreshstatuses.CreateDescribetrustedadvisorcheckrefreshstatusesTool(cfg),
		tools_x_amz_target_awssupport_20130415_resolvecase.CreateResolvecaseTool(cfg),
		tools_x_amz_target_awssupport_20130415_describeservices.CreateDescribeservicesTool(cfg),
		tools_x_amz_target_awssupport_20130415_describecommunications.CreateDescribecommunicationsTool(cfg),
		tools_x_amz_target_awssupport_20130415_createcase.CreateCreatecaseTool(cfg),
		tools_x_amz_target_awssupport_20130415_describecases.CreateDescribecasesTool(cfg),
		tools_x_amz_target_awssupport_20130415_describeseveritylevels.CreateDescribeseveritylevelsTool(cfg),
		tools_x_amz_target_awssupport_20130415_addattachmentstoset.CreateAddattachmentstosetTool(cfg),
		tools_x_amz_target_awssupport_20130415_describetrustedadvisorcheckresult.CreateDescribetrustedadvisorcheckresultTool(cfg),
		tools_x_amz_target_awssupport_20130415_describeattachment.CreateDescribeattachmentTool(cfg),
		tools_x_amz_target_awssupport_20130415_describetrustedadvisorchecksummaries.CreateDescribetrustedadvisorchecksummariesTool(cfg),
	}
}
